index:
  path: /
  controller: App\Routing\Controllers\IndexController::index

test:
  path: /test
  controller: App\Routing\Controllers\IndexController::test

articles_index:
  path: /articles
  controller: App\Routing\Controllers\ArticleController::index

articles_all:
  path: /articles/all
  controller: App\Routing\Controllers\ArticleController::all

articles_get:
  path: /articles/{id}
  controller: App\Routing\Controllers\ArticleController::get
  requirements:
    id: '\d+'

articles_new:
  path: /articles/new
  controller: App\Routing\Controllers\ArticleController::new

articles_create:
  path: /articles/create
  controller: App\Routing\Controllers\ArticleController::create

articles_edit:
  path: /articles/{id}/edit
  controller: App\Routing\Controllers\ArticleController::edit

api/articles_save:
  path: /articles/save
  controller: App\Routing\Controllers\ArticleController::save
  methods: POST

api/articles_remove:
  path: /articles/{id}/remove
  controller: App\Routing\Controllers\ArticleController::remove

user_auth:
  path: /auth
  controller: App\Routing\Controllers\UserController::auth

api/signin:
  path: /api/signin
  controller: App\Routing\Controllers\UserController::signIn
  methods: POST

api/signout:
  path: /api/signout
  controller: App\Routing\Controllers\UserController::signOut

remove_trailing_slash:
  path: /{url}
  controller: App\Routing\Controllers\RedirectController::removeTrailingSlash
  requirements:
    url: .*/$